PKCS11: Support for Object APIs - Finding Objects
OP-TEE/optee_client pull request #244
Opened 2020-12-24 11:09 UTC by ruchi393

2020-12-25 18:27 UTC, vesajaaskelainen commented on libckteec/include/pkcs11_ta.h
> +	PKCS11_CMD_FIND_OBJECTS_INIT = 34,
Shall we allocate 34 for PKCS11_CMD_GENERATE_KEY_PAIR so it would be next to PKCS11_CMD_GENERATE_KEY (33)?

2020-12-28 07:36 UTC, ruchi393 commented on libckteec/include/pkcs11_ta.h
> +	PKCS11_CMD_FIND_OBJECTS_INIT = 34,
Sure, we can do that. I will change it to start from 35.

2020-12-28 07:40 UTC, vesajaaskelainen commented on libckteec/include/pkcs11_ta.h
> +	PKCS11_CMD_FIND_OBJECTS_INIT = 34,
I already started thinking derive key -- what is the really the best thing to do?

If you look at all missing IDs and give proposal?

2020-12-29 05:55 UTC, ruchi393 commented on libckteec/include/pkcs11_ta.h
> +	PKCS11_CMD_FIND_OBJECTS_INIT = 34,
If I look at key management functions, there are 5 of them -> GenerateKey, GenerateKeyPair, WrapKey, UnWrapKey and DeriveKey, but we may not be implementing them all in near future. Thinking more about it, the number allocated to command over here doesn't have much significance, mostly an order in which commands are getting implemented. I am ok to leave 1 number for C_GenerateKeyPair as we are aware we are implementing it currently. For rest, perhaps they can add them as we implement them in this list. 

Anyways, I don't have very strong opinion on this. @etienne-lms , your thoughts ?

2020-12-30 12:28 UTC, vesajaaskelainen commented on libckteec/src/pkcs11_processing.c
> +	release_serial_object(&obj);
reverse order for free's

2020-12-30 12:31 UTC, vesajaaskelainen commented on libckteec/src/pkcs11_processing.c
> +	if (!count || (*count && !obj))
Shouldn't this be:
```c
	if (!count || (max_count && !obj))
```

2020-12-30 12:34 UTC, vesajaaskelainen commented on libckteec/src/pkcs11_processing.c
> +	ckteec_free_shm(ctrl);
reverse order for free's

2020-12-30 12:37 UTC, vesajaaskelainen commented on libckteec/src/pkcs11_processing.c
> +	/* Shm io2: (out) [attributes] */
[object size]

2020-12-30 12:40 UTC, vesajaaskelainen commented on libckteec/src/pkcs11_processing.c
> +		rv = deserialize_ck_attributes(out_shm->buffer, attribs, count);
`rv = ...` loses the return value from the TA.

In TA side it seems to match quite close to specification how it detects different soft error situations.

Then again also the `deserialize_ck_attributes()` returns maybe different return value. So perhaps return values should be in different variables and then decide somehow which takes precedence.

2020-12-30 12:41 UTC, vesajaaskelainen commented on libckteec/src/pkcs11_processing.c
> +	ckteec_free_shm(ctrl);
swap `ctrl` and `out` in frees to have reverse order.

2020-12-31 10:26 UTC, vesajaaskelainen commented on libckteec/src/pkcs11_processing.c
> +		rv = deserialize_ck_attributes(out_shm->buffer, attribs, count);
Played around with this and ended up with:
- https://github.com/vesajaaskelainen/optee_os/commit/a17fbda6cccaad3be83d270fe54a62e67e07eb0e
- https://github.com/vesajaaskelainen/optee_client/commit/5f1689a0a1dbe2f137af2b25b27022adc646fe00

And now my tests seem to pass again.

2021-01-04 08:05 UTC, etienne-lms reviewed
I looked back in the implementation of this and actually  @EDVTAZ is also to credit for these find/get functions.
I suggest to add:
```
Co-developed-by: Gabor Szekely <szvgabor@gmail.com>
Signed-off-by: Gabor Szekely <szvgabor@gmail.com>
```
This stands for the `optee_os` parts of the commands also.

2021-01-04 08:26 UTC, vesajaaskelainen commented on libckteec/src/pkcs11_processing.c
> +		rv = deserialize_ck_attributes(out_shm->buffer, attribs, count);
Why I went with priority for TA value was that it was better overall status how well the operation went and in theory it should be complete error value. Client side has just some error or no error style of life. In specification there is priority order for error values and I believe only TA tries to do that. But we could still catch some serialization error or so if TA didn't have error then additional error from client would be used.

2021-01-05 08:13 UTC, ruchi393 commented on libckteec/include/pkcs11_ta.h
> +	PKCS11_CMD_FIND_OBJECTS_INIT = 34,
I will leave it is then.

2021-01-05 11:16 UTC, ruchi393 commented on libckteec/src/pkcs11_processing.c
> +		rv = deserialize_ck_attributes(out_shm->buffer, attribs, count);
What are the scenarios where deserialize_ck_attributes() would return an error ? IIUC this would not be only in cases where the way attributes have been understood or packed by TA is not correct . I believe this would not be a usual scenario. Is this understanding correct ? If yes, then probably what @etienne-lms has suggested should work.

if (rv == CKR_OK || rv == CKR_ATTRIBUTE_SENSITIVE ||
    rv == CKR_ATTRIBUTE_TYPE_INVALID || rv == CKR_BUFFER_TOO_SMALL) {
		rv2 = deserialize_ck_attributes(out_shm->buffer, attribs,
						count);
		if (rv2)
			rv = rv2;
}

2021-01-05 11:28 UTC, etienne-lms commented on libckteec/src/pkcs11_processing.c
> +		rv = deserialize_ck_attributes(out_shm->buffer, attribs, count);
> What are the scenarios where deserialize_ck_attributes() would return an error ?

I think the only way to have this case if that pkcs11 TA is not compliant in some way. TA ABI issue. This is not expected, but I think it should be caught and reported if occurring.
Maybe if we should force `rv = PKCS11_CKR_GENERAL_ERROR` regardless non-`CKR_OK` value returned by `deserialize_ck_attributes()`.

2021-01-05 12:02 UTC, ruchi393 commented on libckteec/src/pkcs11_processing.c
> +	/* Shm io2: (out) [attributes] */
Fixed

2021-01-05 12:02 UTC, ruchi393 commented on libckteec/src/pkcs11_processing.c
> +	ckteec_free_shm(ctrl);
Changed at all places

2021-01-05 12:02 UTC, ruchi393 commented on libckteec/src/pkcs11_processing.c
> +	if (!count || (*count && !obj))
Changed

2021-01-05 12:03 UTC, ruchi393 commented
> I looked back in the implementation of this and actually @EDVTAZ is also to credit for these find/get functions.
> I suggest to add:
> 
> ```
> Co-developed-by: Gabor Szekely <szvgabor@gmail.com>
> Signed-off-by: Gabor Szekely <szvgabor@gmail.com>
> ```
> 
> This stands for the `optee_os` parts of the commands also.

Thanks @etienne-lms . Will add the credit when I squash and apply tags

2021-01-05 12:52 UTC, etienne-lms commented
If @vesajaaskelainen agrees, I think you can squash the fixup commits into the series and get CI status.

2021-01-06 19:23 UTC, vesajaaskelainen commented
> If @vesajaaskelainen agrees, I think you can squash the fixup commits into the series and get CI status.

I can review it as a whole so no problem for me.

2021-01-06 19:26 UTC, vesajaaskelainen commented on libckteec/src/pkcs11_processing.c
> +		rv = deserialize_ck_attributes(out_shm->buffer, attribs, count);
If you want to give priority for return values from deserialize_ck_attributes() then similar priority checks need to be done in deserialize_ck_attributes() what is done in TA side. Currently it doesn't do it that well.

2021-01-07 18:15 UTC, ruchi393 commented on libckteec/src/pkcs11_processing.c
> +		rv = deserialize_ck_attributes(out_shm->buffer, attribs, count);
sorry, @vesajaaskelainen  I didn't fully understand what change you are suggesting.  Can you clarify.

The only reason deserialize_ck_attributes() can return error is if the pkcs#11 TA is not compliant with the client side , hence mismatch in serialization and de-serialization. So this would not be a normal case.  May be I am missing something out.

2021-01-07 18:15 UTC, ruchi393 commented on libckteec/src/pkcs11_processing.c
> +	ckteec_free_shm(ctrl);
Done

2021-01-07 18:19 UTC, ruchi393 commented
Rebased and squashed the commits for easier review

2021-01-08 11:14 UTC, etienne-lms requested changes
checkpatch reported issues for "libckteec: add support for Object Function".

2021-01-08 11:14 UTC, etienne-lms commented on libckteec/src/pkcs11_processing.c
> +	if (!out_shm){
checkpatch; add a space char.

2021-01-08 11:14 UTC, etienne-lms commented on libckteec/src/pkcs11_processing.c
> +	    goto bail;
checkpatch: indentation (replace space chars with a tab)

2021-01-08 11:14 UTC, etienne-lms commented on libckteec/src/pkcs11_processing.c
> +	if (!out_shm){
checkpatch: add a space char

2021-01-08 11:14 UTC, etienne-lms commented on libckteec/src/pkcs11_processing.c
> +				       ctrl, out_shm, &out_size);
checkpatch: indent to parenthesis.

2021-01-08 11:17 UTC, etienne-lms reviewed
checkpatch reported issues in commit "libckteec: helper function to deserialize a attribute template".

2021-01-08 11:17 UTC, etienne-lms commented on libckteec/src/serialize_ck.c
> +	/* These are serialized each seperately */
checkpatch: s/seperately/separately/

2021-01-08 11:17 UTC, etienne-lms commented on libckteec/src/serialize_ck.c
> +		 * Can't trust size becuase it was set to reflect
checkpatch: s/becuase/because/

2021-01-08 11:33 UTC, ruchi393 commented
@etienne-lms , sorry, my bad. I missed checking checkpatch errors for this PR. I will fix these.

2021-01-08 15:50 UTC, vesajaaskelainen commented on libckteec/src/pkcs11_processing.c
> +	if (rv == CKR_OK || rv == CKR_BUFFER_TOO_SMALL ||
`CKR_BUFFER_TOO_SMALL` is now two times here.

Change the first one to `CKR_ATTRIBUTE_SENSITIVE`.

2021-01-08 16:56 UTC, etienne-lms commented on libckteec/src/pkcs11_processing.c
> +	if (rv == CKR_OK || rv == CKR_BUFFER_TOO_SMALL ||
+1
```c
	if (rv == CKR_OK || rv == CKR_ATTRIBUTE_SENSITIVE ||
	    rv == CKR_ATTRIBUTE_TYPE_INVALID || rv == CKR_BUFFER_TOO_SMALL) {

2021-01-08 17:40 UTC, vesajaaskelainen commented on libckteec/src/pkcs11_processing.c
> +	struct serializer sattr;
```
	struct serializer sattr = { 0 };
```

2021-01-08 17:41 UTC, vesajaaskelainen commented on libckteec/src/serialize_ck.c
> +			(struct pkcs11_attribute_head *)(void *)curr_head;
double cast -- isn't one enough?

2021-01-08 17:45 UTC, vesajaaskelainen commented on libckteec/src/pkcs11_processing.c
> +		rv = deserialize_ck_attributes(out_shm->buffer, attribs, count);
I'll come back to this return value discussion in the PR for the fixes. It might be something that can be adjusted in the go now that the return logic has been tuned up.

2021-01-08 18:52 UTC, etienne-lms commented on libckteec/src/serialize_ck.c
> +			(struct pkcs11_attribute_head *)(void *)curr_head;
agree, cast to `void *` should be enough.

2021-01-09 11:13 UTC, vesajaaskelainen commented on libckteec/src/serialize_ck.c
> +			(struct pkcs11_attribute_head *)(void *)curr_head;
As lot of time we write also C++ it is quite common to cast to actual target type.

That would cause C's implicit void * cast to another pointer type to happen. 

Not to confuse people I would probably cast it to (struct pkcs11_attribute_head *) as that is target type. 

But I can understand either version so I let you pick the style.

2021-01-11 06:34 UTC, ruchi393 commented
Fixed review comments

2021-01-11 08:15 UTC, etienne-lms commented on libckteec/src/pkcs11_processing.c
> +
check patch will complain for the empty line above.
can remove it, and maybe line 878 also.

2021-01-12 08:48 UTC, vesajaaskelainen commented
Feel free to squash fixes when available.

2021-01-12 09:51 UTC, ruchi393 commented
Squashed and pushed for review

2021-01-12 13:13 UTC, etienne-lms reviewed
very minor comments for commit "libckteec: helper function to deserialize a attribute template".

few changes in 3rd commit to move to 2nd commit.

2021-01-12 13:13 UTC, etienne-lms commented on libckteec/src/serialize_ck.c
> +	return rv;
```c
	return deserialize_ck_attributes(obj->data, attr, count);
```
removes line 86.
	return rv;

2021-01-12 13:13 UTC, etienne-lms commented on libckteec/src/serialize_ck.c
> +	 * not pkcs11_object_head, so we need to correct the pointer
I suggest to remove this inline comment

2021-01-12 13:13 UTC, etienne-lms commented on libckteec/include/pkcs11_ta.h
> +	 *                   data
this change in commit "libckteec: add support for Object Function" should be squashed in previous commit "libckteec: sync with pkcs11 ta api for object related commmands".

Ditto 4 lines below.

2021-01-13 05:13 UTC, ruchi393 commented
Fixed the issues with squashing and comment on deserialize commit. Thanks @etienne-lms for catching them.

2021-01-13 16:07 UTC, vesajaaskelainen commented
For commits:
- https://github.com/OP-TEE/optee_client/pull/244/commits/e1619a699b6be91612c76c8497e2f8d17aa342ad
- https://github.com/OP-TEE/optee_client/pull/244/commits/2bb91be33191487fc32e7aaa99e99acb7b6833d1
- https://github.com/OP-TEE/optee_client/pull/244/commits/022154374087c0fd786265d37813d1f0189b140c
- https://github.com/OP-TEE/optee_client/pull/244/commits/162ce70144011e164e848d81df0a556a21aade0c

`Reviewed-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>`

Commit:
- https://github.com/OP-TEE/optee_client/pull/244/commits/b6531505e1b5b078802067173bce94a87e6780b8 still needs a bit work on commit message.

Perhaps "libckteec: add support for Object Function" -> "libckteec: add support for get object size and get attribute value"

with that or similar clarification:

`Reviewed-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>`

2021-01-13 17:29 UTC, ruchi393 commented
Commit reworded and Tags applied 

Thanks @vesajaaskelainen and @etienne-lms

2021-01-13 18:18 UTC, merged