libapduteec: interface to send APDU frames to a secure element
OP-TEE/optee_client pull request #290
Opened 2021-11-05 08:02 UTC by ldts

A secure element might be configured by OP-TEE; if the SE enabled
SCP03, the encryption key should have been derived from the HUK and
never known to the normal world. In such circumstances, APDU frames
will need to be routed by the secure world as it is the only one with
access to the SCP03 keys.

A working scenario currently in OP-TEE is the NXP SE050.

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

2021-11-05 08:56 UTC, jforissier reviewed
I think you should drop the pthread stuff (let the caller deal with thread safety if needed) and add initialization and finalization functions. That would make things much simpler IMO. Or do you have specific scenarios in mind for this library?

2021-11-05 08:56 UTC, jforissier commented on libapduteec/src/apdu.c
> +__attribute__((constructor)) static int apdu_init(void)
Why not provide a public API function for this? Then the caller could deal with errors.

2021-11-05 08:56 UTC, jforissier commented on libapduteec/src/apdu.c
> +		exit(EXIT_FAILURE);
Killing the whole process just because one library could not initialize is quite drastic!

2021-11-05 08:56 UTC, jforissier commented on libapduteec/src/apdu.c
> +	e = pthread_mutex_lock(&ta_ctx.init_mutex);
What is this protecting against?

2021-11-05 12:48 UTC, ldts commented on libapduteec/src/apdu.c
> +__attribute__((constructor)) static int apdu_init(void)
yes I agree. But I'd rather let the client handle it before main executes - ie, as early as possible. Will use a signal for that.

2021-11-05 12:49 UTC, ldts commented on libapduteec/src/apdu.c
> +		exit(EXIT_FAILURE);
right, pkcs#11 is doing the same thing...I am not sure is a good idea either. In any case, since the constructor is establishing the session I have no need for this lock so will remove.

2021-11-05 13:11 UTC, ldts commented on libapduteec/src/apdu.c
> +__attribute__((constructor)) static int apdu_init(void)
ie: https://github.com/ldts/apdu/blob/master/main.c#L143

2021-11-05 13:16 UTC, ldts commented
um, IBART is failing with: @jbech-linaro 

Resolving deltas: 100% (283/283), completed with 91 local objects.
    17:  
    18:  Your identity is: Joakim Bech <joakim.bech@linaro.org>
    19:  If you want to change this, please re-run 'repo init' with --config-name
    20:  
    21:  repo has been initialized in /home/optee/devel/hikey
    22:  0
    23:  IBART $ repo sync -j4;echo $?
    24:  
    25:  ... A new version of repo (2.17) is available.
    26:  ... You should upgrade soon:
    27:      cp /home/optee/devel/hikey/.repo/repo/repo /home/optee/bin/repo

2021-11-05 13:18 UTC, jforissier commented
@ldts it is just a warning, not supposed to be fatal, I suspect a timeout. I am restarting the job and we'll see.

2021-11-05 17:03 UTC, etienne-lms commented on libapduteec/include/apdu_ta.h
> + * ADPU based communication with the SE05X secure element
Again, is this library targeting only SE05x devices?

2021-11-05 17:13 UTC, ldts commented on libapduteec/include/apdu_ta.h
> + * ADPU based communication with the SE05X secure element
no it is supposed to target any device...I guess I imported an old file. 
I'll reword.

2021-11-08 06:05 UTC, etienne-lms reviewed
> during initialization, the library will raise the SIGABRT signal
therefore giving the client the chance to start its main program in a
different mode.

A better way IMO is to have initialization and termination API functions for this library. It's more flexible for a client to call some `C_APDU_Initialize()` and deal with result rather that trapping a signal.

2021-11-08 08:18 UTC, jenswi-linaro commented on libapduteec/include/apdu_ta.h
> +/* SPDX-License-Identifier: BSD-3-Clause */
This library is about abstracting this so perhaps this file should go into `libapduteec/src`.

2021-11-08 08:18 UTC, jenswi-linaro commented on libapduteec/src/apdu.c
> +__attribute__((constructor(1000))) static void apdu_init(void)
I agree, this sort of thing seems to cause more troubles than it solves.

2021-11-08 08:18 UTC, jenswi-linaro commented on libapduteec/include/apdu.h
> +/* The library throws SIGABRT before the main is executed - the main program can
How is `main()` supposed to catch that?

2021-11-08 08:18 UTC, jenswi-linaro commented on libapduteec/src/apdu.c
> +					 TEEC_MEMREF_WHOLE,
How about using `TEEC_MEMREF_*` instead and let `TEEC_InvokeCommand()` do the buffer handling?

2021-11-08 08:22 UTC, ldts commented on libapduteec/src/apdu.c
> +__attribute__((constructor(1000))) static void apdu_init(void)
ok, we can do that. @etienne-lms 
ah, you mean we dont need to issue the TEEC_CloseSession before the termination of the process (on destruction)?

2021-11-08 08:34 UTC, etienne-lms commented on libapduteec/src/apdu.c
> +__attribute__((constructor(1000))) static void apdu_init(void)
yes. libteec and tee/optee drivers release all OP-TEE resources related to the task when the task ends.

2021-11-08 08:46 UTC, ldts commented on libapduteec/include/apdu.h
> +/* The library throws SIGABRT before the main is executed - the main program can
@jenswi-linaro just using a higher priority constructor...but it doesnt matter, will remove the constructor thingy.

2021-11-08 08:47 UTC, ldts commented on libapduteec/src/apdu.c
> +__attribute__((constructor(1000))) static void apdu_init(void)
ah, great. ok.

2021-11-08 09:12 UTC, ldts commented on libapduteec/src/apdu.c
> +					 TEEC_MEMREF_WHOLE,
@jenswi-linaro I dont understand, could you give me some more info/reference please?

2021-11-08 09:54 UTC, jenswi-linaro commented on libapduteec/src/apdu.c
> +					 TEEC_MEMREF_WHOLE,
For example:
https://github.com/OP-TEE/optee_test/blob/13c4de15fa0370bfd37de476f02c103fd47ccc47/host/xtest/regression_1000.c#L272-L275

Skimming through the TEE Client API specification should give some more background.

2021-11-08 10:50 UTC, ldts commented on libapduteec/src/apdu.c
> +					 TEEC_MEMREF_WHOLE,
@jenswi-linaro ah you mean for param#0?

2021-11-08 11:55 UTC, etienne-lms commented on libapduteec/src/apdu.c
> +					 TEEC_MEMREF_WHOLE,
Instead of allocating share dmemory, you can pass stright your buffer reference:

```c
	op.paramTypes = TEEC_PARAM_TYPES(TEEC_VALUE_INPUT,
					 TEEC_MEMREF_TEMP_INPUT,
					 TEEC_MEMREF_TEMP_INPUT,
					 TEEC_MEMREF_TEMP_OUTPUT);
	op.params[0].value.a = type;
	op.params[1].tmpref.buffer = hdr;
	op.params[1].tmpref.size = hdr_len;
	op.params[2].tmpref.buffer = src;
	op.params[2].tmpref.size = src_len;
	op.params[3].tmpref.buffer = dst;
	op.params[3].tmpref.size = dst_len;

2021-11-08 12:42 UTC, jenswi-linaro commented on libapduteec/src/apdu.c
> +					 TEEC_MEMREF_WHOLE,
Thanks, spot on Etienne.

2021-11-08 12:52 UTC, ldts commented on libapduteec/src/apdu.c
> +					 TEEC_MEMREF_WHOLE,
ah ok. so the same would apply to the the pkcs11 library then?

2021-11-08 13:52 UTC, ldts commented on libapduteec/include/apdu.h
> +int C_APDU_request(enum apdu_type type,
many thanks for this

2021-11-08 13:54 UTC, ldts commented on libapduteec/include/apdu.h
> +enum apdu_type {
@etienne-lms what do you mean? why is this not enough?

2021-11-08 14:02 UTC, etienne-lms commented on libapduteec/src/apdu.c
> +					 TEEC_MEMREF_WHOLE,
Could be yes. However, looking back into the code, I didn't find places where such scheme would apply. Maybe I missed them. Feel free to propose a P-R if there are places where such sequence would simply libckteec implementation.

2021-11-08 14:04 UTC, etienne-lms commented on libapduteec/include/apdu.h
> +enum apdu_type {
please, provide a definition of what is an APDU type and which value is expected for this argument.

2021-11-08 14:06 UTC, etienne-lms commented on libapduteec/include/apdu.h
> +int C_APDU_request(enum apdu_type type,
btw, don't forget `@return 0     Success`

2021-11-08 17:20 UTC, ldts commented on libapduteec/include/apdu.h
> +enum apdu_type {
Would something like this work? 

I don't know what other drivers might need but the NXPSE050 uses three types to indicate if the response must be dropped and or if the raw frame is in the[ extended format.](https://docs.oracle.com/en/java/javacard/3.1/guide/extended-apdu-format.html#GUID-0F452782-9402-43E9-B39C-337772C200DF)

These types are driver specific and I expect -as in the case of the SE05X, that the driver itself will be outside of the OP-TEE repository in an external library.

```

/**
 * Device specific  requestflags to help the driver process the frames.
 *
 * Can be used to indicate if the APDU frame is of an extended type or if the
 * response frame to a particular request should be dropped.
 */
```

2021-11-08 17:48 UTC, ldts commented on libapduteec/include/apdu.h
> +int C_APDU_request(enum apdu_type type,
argh ok

2021-11-09 07:50 UTC, jenswi-linaro commented on libseteec/include/se.h
> +int C_SE_apdu_request(enum se_apdu_type type,
Are these function names following any standard? If not how about s/C_SE_/se_/?

2021-11-09 08:44 UTC, ldts commented on libseteec/src/se.c
> +	return 0;
sorry, fixing this

2021-11-09 11:19 UTC, etienne-lms commented on libseteec/include/se.h
> + * Device specific request flags to help the driver process the frames.
So application should know which device is used?

2021-11-09 11:19 UTC, etienne-lms commented on libseteec/include/se.h
> + * response frame to a particular request should be dropped.
Can you give a pointer explaining which type relates to which extension/response/...?

2021-11-09 13:04 UTC, ldts commented on libseteec/src/scp03_ta.h
> + * [in]     value[0].a    extra option (0 do not rotate keys, 1 rotate keys)
@etienne-lms, please do not worry - your questions are always challenging - and welcome!- and more often than not uncover important issues

To clarify, the rotate request corresponds to the PUTKEY command.

Notice that it must be captured in GP specs because to enable SCP03,  SCP03 **must be running already** with some default keys.  So, it would be strange if the user is not allowed by design - and captured in the specification- to modify those default keys (this is key rotation).

Hence why this is a generic interface and not NXP SE050 specific.

2021-11-10 09:46 UTC, ldts commented on libseteec/src/apdu_ta.h
> +#define TA_CMD_TXRX_APDU_RAW_FRAME		0
I'd rather keep the APDU_RAW_FRAME: the type is the type of raw frame

2021-11-10 09:49 UTC, ldts commented on libseteec/src/se.c
> +		return -EINVAL;
@etienne-lms why can we leave it open for another request? the user will be sending many APDUs over a period of time

2021-11-10 09:50 UTC, ldts commented on libseteec/src/se.c
> +	EMSG("Processing in the Secure Element failed, -EIO");
EACCESS

2021-11-10 09:50 UTC, ldts commented on libseteec/include/se.h
> + * Generates the board specific SCP03 keys and writes them in the Secure Element
C_se_scp03_generate_keys() ?

2021-11-10 09:51 UTC, ldts commented on libseteec/include/se.h
> +#define SE_H
se_tee.h

2021-11-10 10:00 UTC, jenswi-linaro commented on libseteec/include/se.h
> + * Generates the board specific SCP03 keys and writes them in the Secure Element
Why should we have a `C_` prefix?

2021-11-10 10:13 UTC, ldts commented on libseteec/include/se.h
> + * Device specific request flags to help the driver process the frames.
finally found the reference in the spec. fixing it.

2021-11-10 10:13 UTC, ldts commented on libseteec/include/se.h
> + * response frame to a particular request should be dropped.
yes, will be in the header

2021-11-10 10:37 UTC, ldts commented on libseteec/include/se.h
> + * Generates the board specific SCP03 keys and writes them in the Secure Element
right, @etienne-lms I was wondering the same thing, could you clarify please?

2021-11-10 10:51 UTC, etienne-lms commented on libseteec/include/se.h
> + * Generates the board specific SCP03 keys and writes them in the Secure Element
drop the `C_`, I agree we don't need it.  My concern was rather on `rotate_keys` that should rather be `generate_keys`.

2021-11-10 11:00 UTC, etienne-lms commented on libseteec/src/apdu_ta.h
> +#define TA_CMD_TXRX_APDU_RAW_FRAME		0
For consistency among PTA APIs, prefer command ID macros as `PTA_<pta-short-name>_XXX` as almost all PTA command IDs are defined.
Here: `PTA_APDU_CMD_TXRX_RAW_FRAME` or `PTA_APDU_TXRX_RAW_FRAME`.

Side note: raw frame would rather expect raw data, hence no TYPE hint value. If a type hint is passed by the command then `PTA_APDU_CMD_TXRX_TYPED_FRAME` would be more explicit IMO. Yet, not a strong opinion.

2021-11-10 14:47 UTC, ldts commented on libseteec/include/se.h
> + * Generates the board specific SCP03 keys and writes them in the Secure Element
but it wont be just generating keys, it will be rotating the keys - ie, replacing the running keys in the device - because they must be in execution while this is happening- with new keys. there is a distinction...

2021-11-10 14:50 UTC, ldts commented
@etienne-lms @jenswi-linaro I think all comments have now been addressed.

2021-11-10 14:53 UTC, jenswi-linaro commented
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

2021-11-10 16:35 UTC, ldts commented on libseteec/src/apdu_ta.h
> +#define TA_CMD_TXRX_APDU_RAW_FRAME		0
@etienne-lms um...ok, I thought you had asked before to remove the PTA_ prefix for TA_...so I did. 
But ok, will put it back to how it was - and how it is in OP-TEE....maybe I misunderstood.

The frames can be RAW or SCP03 ENCRYPTED.; this is the reason for the PTA...RAW frames that dont need to be SCP03 enrypted could be placed on the bus any time without requirement OP-TEE; it is only when SCP03 has been enabled - and the keys are in the secure world - that the interface makes sense. So the interface will only work for RAW frames hence why I wanted to be explicit and clear about it. The type is the actual type of APDU frame...not whether the frame is encrypted or not.

2021-11-10 20:16 UTC, etienne-lms commented on libseteec/include/se_tee.h
> + * @return -EACCESS	Secure element processing error
`EACCES Permission denied (POSIX.1-2001).`
You should use another errno for that error.

2021-11-10 20:16 UTC, etienne-lms commented on libseteec/include/se_tee.h
> + * @return -EAGAIN	Initialization mutex not available
` * @return -EAGAIN	Mutex consumer count overflow`

2021-11-10 20:16 UTC, etienne-lms commented on libseteec/include/se_tee.h
> + * @return -EINVAL	On error
This function can also return `-EAGAIN`, `-ENODEV` and `-EPERM`.
Ditto for `se_scp03_rotate_keys()`.

2021-11-10 20:16 UTC, etienne-lms commented on libseteec/include/se_tee.h
> +
remove the empty line

2021-11-11 06:23 UTC, ldts commented on libseteec/include/se_tee.h
> + * Generates the board specific SCP03 keys and writes them in the Secure Element
um ok, I can do that but this IMO is common knowledge...

2021-11-11 06:28 UTC, ldts commented on libseteec/src/se.c
> +	if (*dst_len)
why do you need the logic here? this is not a driver...the actual driver can determine if there is an error and set dst_len to zero. I thought it was cleaner this way. But I can change it if you insist.

2021-11-11 06:30 UTC, ldts commented on libseteec/src/se.c
> +	op.params[0].value.a = 1;
right, but the proper way for doing this would be to commit the change to OP-TEE first and then update the pta_scp03.h...but sure I can pick this up.

2021-11-11 06:32 UTC, ldts commented on libseteec/include/se_tee.h
> +	SE_APDU_CASE_INVALID = 0xFF,
nah it is useful - maybe this is not the best name possible but passing an _invalid case_ will cause the driver to try to identify the case from the frame itself.

2021-11-11 06:33 UTC, ldts commented on libseteec/include/se_tee.h
> +	SE_APDU_CASE_1 = 0x0,
right, tried to be very explict here but ok

2021-11-11 06:33 UTC, ldts commented on libseteec/include/se_tee.h
> +/* As described in Smart Card Standard ISO7816-4 5.3 ADPU message structure */
ok

2021-11-11 06:34 UTC, ldts commented on libseteec/include/se_tee.h
> + * se_apdu_request() - Send an APDU message and get response
right, INVALID was doing the no_hint. no_hint a much better name. will change that

2021-11-11 06:43 UTC, ldts commented on libseteec/include/se_tee.h
> + * Generates the board specific SCP03 keys and writes them in the Secure Element
actually no, the description is good but let me add some more info.
```
/**
 * se_scp03_rotate_keys()  - Rotate the default SCP03 keys
 *
 * Generates the SCP03 unique keys for the board and writes them in the Secure
 * Element non volatile memory.
 *
 * The SCP03 keys must persist also in the secure world across reboots so the
 * keys written in the Secure Element must have been either derived from  some
 * secret or stored in secure storage
 * /
```

2021-11-11 07:07 UTC, ldts commented on libseteec/include/se_tee.h
> + * @return -EACCESS	Secure element processing error
we dont know why the SE will be failing to process - could perfectly be EACCES if the session is rejected.

2021-11-11 07:08 UTC, ldts commented on libseteec/include/se_tee.h
> + * @return -EAGAIN	Initialization mutex not available
yes but I chose to use this error as it is the most common one - instead of describing all the possible mutex problems...gets tricky

2021-11-11 07:11 UTC, ldts commented on libseteec/include/se_tee.h
> + * @return -EAGAIN	Initialization mutex not available
The pthread_mutex_lock() and pthread_mutex_trylock() functions shall fail if:

       EAGAIN The mutex could not be acquired because the maximum number of recursive locks for mutex has been exceeded.

       EINVAL The mutex was created with the protocol attribute having the value PTHREAD_PRIO_PROTECT and the calling thread's  priority
              is higher than the mutex's current priority ceiling.

       ENOTRECOVERABLE
              The state protected by the mutex is not recoverable.

       EOWNERDEAD
              The mutex is a robust mutex and the process containing the previous owning thread terminated while holding the mutex lock.
              The mutex lock shall be acquired by the calling thread and it is up to the new owner to make the state consistent.

2021-11-11 07:12 UTC, ldts commented on libseteec/include/se_tee.h
> + * @return -EAGAIN	Initialization mutex not available
do we need all of these unlikely errors in the header? seems excessive...

2021-11-11 07:15 UTC, ldts commented on libseteec/include/se_tee.h
> + * @return -EINVAL	Invalid arguments regarding an APDU message
but on error, TEE_IOC_INVOKE will return 

static TEEC_Result ioctl_errno_to_res(int err)
{
	switch (err) {
	case ENOMEM:
		return TEEC_ERROR_OUT_OF_MEMORY;
	case EINVAL:
		return TEEC_ERROR_BAD_PARAMETERS;
	default:
		return TEEC_ERROR_GENERIC;
	}
}

2021-11-11 07:25 UTC, ldts commented on libseteec/include/se_tee.h
> + * Generates the board specific SCP03 keys and writes them in the Secure Element
what about:
```
 * se_scp03_rotate_keys_and_enable() - Rotate the default SCP03 keys and Enable
 * the SCP03 session
 *
 * Generates the SCP03 unique keys for the board and writes them in the Secure
 * Element non volatile memory.
 *
 * The SCP03 session with the Secure Element is kept enabled.
 *
 * The SCP03 keys must persist also in the secure world across reboots so the
 * keys written in the Secure Element must have been either derived from  some
 * secret or stored in secure storage.
```

2021-11-11 07:27 UTC, ldts commented on libseteec/include/se_tee.h
> +	SE_APDU_CASE_INVALID = 0xFF,
but will use the name you proposed further down in the review. much better choice.

2021-11-11 07:47 UTC, etienne-lms commented on libseteec/include/se_tee.h
> + * @return -EAGAIN	Initialization mutex not available
Agree. You legitimately prepared the mutex so this only reason `pthread_mutex_lock()` could fail is with EAGAIN.

2021-11-11 07:50 UTC, etienne-lms commented on libseteec/include/se_tee.h
> + * @return -EACCESS	Secure element processing error
If there's no SE device or PTA fails to connect to the SE for some _TEE or Secure element processing error_, the failure is not due to an access permission issue.

2021-11-11 08:06 UTC, etienne-lms commented on libseteec/include/se_tee.h
> + * Generates the board specific SCP03 keys and writes them in the Secure Element
sorry to insist. I am a newby to SCP03 and I don't know what is key rotation.
From the description, i don't understand why the function is labeled `..._rotate_keys()`. Looking a SCP03 docs I can find any reference to key rotation features. Wwwebing for secure element and key rotation information does not bring much help. 

The last section in this description is a nice informative notice, but I don't think it explains what this function does.

Do you mean the below?
```
/*
 * se_scp03_rotate_keys_and_enable() - Rotate the default SCP03 keys and Enable
 * the SCP03 session
 *
 * Generates the SCP03 unique keys for the board and writes them in the Secure
 * Element non volatile memory if not already stored. Rotate the key used for SCP03
 * session among generated unique keys.
 *
 * The SCP03 session with the Secure Element is kept enabled, based on the key
 * selected by the key rotation operation.
 */
```
Note the above description is still confusing to me but i'll try to make the effort.
Rotating means you select the next key in the series of the SCP03 keys that have been provisioned, am I right?

2021-11-11 08:08 UTC, etienne-lms commented on libseteec/src/se.c
> +	if (*dst_len)
another way, which looks fine to me is to not test `*dst_len` and let caller decide upon reponse buffer size and content whether the transmission was successful or not.

2021-11-11 08:08 UTC, etienne-lms commented on libseteec/src/se.c
> +	op.params[0].value.a = 1;
thanks

2021-11-11 19:08 UTC, ldts commented on libseteec/include/se_tee.h
> + * Generates the board specific SCP03 keys and writes them in the Secure Element
sorry didnt notice this comment. yes so rotation is to do with symmetric cryptography: basically the user replaces an active key with another one(SCP03 uses symmetric crypto btw)
https://cloud.google.com/kms/docs/key-rotation

The actual implementation varies though; for the SE050, since we didnt want to store any keys on the platform, the rotation call just derives the SCP03 keys from the platform HUK and the SE050 unique id. Ideally the user should only do this once the platform has been secured and the HUK is the final secret one ...if the HUK was to change, the SE050 would be bricked.
Other implementations might choose to use secure storage and then allow to rotate at any time - we also have support for that but we didnt push it upstream as for us it wasnt worth the risk of losing the keys.

2021-11-12 06:57 UTC, etienne-lms commented on libseteec/include/se_tee.h
> + * Generates the board specific SCP03 keys and writes them in the Secure Element
What you describe here is a key generation scheme, being based on derivation, rotation or whatever, this remain generating the key to be used for some service. Again I think the description here should explain what rotation is: re-generating a new session key based on some derivation schemes known from client (TEE) and service (SE device).

2021-11-12 08:10 UTC, ldts commented
@etienne-lms I opted for simplifying the error messages returned by these APIs - I saw no clear benefit on obscuring the code when debugging issues will most likely require rebuilding it anyways.

2021-11-12 08:52 UTC, etienne-lms commented on libseteec/include/se_tee.h
> +	SE_APDU_NO_HINT,
NO_HINT should be in 1st position IMO.
It would make more sense if the spec evolves, and a CASE_5 in introduced.

2021-11-12 08:52 UTC, etienne-lms commented on libseteec/include/se_tee.h
> + * storage.
this description goes far beyond what this API function is expected to describe. Don't describe a device specific behavior in this header file exported by the library.

2021-11-12 08:52 UTC, etienne-lms commented on libseteec/src/se.c
> +	return (pthread_mutex_unlock(&ctx->lock) || res) ? false : true;
`return !pthread_mutex_unlock(&ctx->lock) && !res;`

2021-11-12 08:52 UTC, etienne-lms commented on libseteec/src/se.c
> +		return -EPERM;
Why always `-EPERM`? It should report a real permission error, not a communication issue or the fact the companion OP-TEE does not embedded the expected PTA.
For example, if mutex_lock returns EAGAIN, at line 68 will return  EPERM. A test enviroment or a real application may misbehave if getting the wrong error code.

2021-11-12 09:40 UTC, jenswi-linaro commented on libseteec/include/se_tee.h
> + * @return -EPERM	Operation not permitted.
Error codes in POSIX Pthreads are returned as plain errno values without an explicit negation in front.
In kernels it's common to return like you're doing here, but this is user space so we should probably try follow the established convention here instead.
Or do you have some specific reason why you'd like to return negative values?

2021-11-12 10:46 UTC, ldts commented on libseteec/src/se.c
> +		return -EPERM;
If it misbehaves it is because it is not reading this API. Misbehaving assumes the handling of the error code is wrong. Eperm is correct to indicate that the call failed. To me the finer granularity is not worth the effort in time nor maintenance

2021-11-12 10:48 UTC, ldts commented on libseteec/include/se_tee.h
> + * @return -EPERM	Operation not permitted.
You are right. Will fix

2021-11-12 11:33 UTC, etienne-lms commented on libseteec/include/se_tee.h
> + * @return -EPERM	Operation not permitted.
i think it is me that pointed @ldts forgot the minus signs.
my bad :some-emoji-telling-i-m-sorry:

2021-11-13 16:59 UTC, ldts commented on libseteec/include/se_tee.h
> + * storage.
this is a very dangerous operation that can brick boards...I think the extra information might be beneficial

2021-11-13 17:01 UTC, ldts commented on libseteec/src/se.c
> +		return -EPERM;
but yes EPERM is probably misleading...will use new SE error codes instead.

2021-11-16 15:40 UTC, etienne-lms commented on libseteec/include/se_tee.h
> + * state and the keys are derived from the HUK instead of read from secure
"... instead of **being** read ..."

2021-11-16 15:40 UTC, etienne-lms commented on libseteec/include/se_tee.h
> + * state and the keys are derived from the HUK instead of read from secure
If keys are derived from the HUK, as far as HUK does not change, derived keys will be the same. The fact HUK may change is out of scope I think. Default generation of the RPMB key use the same scheme. If HUK changes, RPMB will be lost its accesses bricked. How different SCP03 keys are?

2021-11-16 15:40 UTC, etienne-lms commented on libseteec/src/apdu_pta.h
> + * [in]  memref[2].buffer     source data (raw APDU request frame data).
for consistency:
s/source/Source/g
s/response/Response/g

2021-11-16 20:41 UTC, ldts commented on libseteec/include/se_tee.h
> + * state and the keys are derived from the HUK instead of read from secure
> "... instead of **being** read ..."

how sure are you about that correction?

2021-11-16 20:43 UTC, ldts commented on libseteec/include/se_tee.h
> + * state and the keys are derived from the HUK instead of read from secure
> If keys are derived from the HUK, as far as HUK does not change, derived keys will be the same. The fact HUK may change is out of scope I think. Default generation of the RPMB key use the same scheme. If HUK changes, RPMB will be lost its accesses bricked. How different SCP03 keys are?

is exactly the same case...however RPMB is a better known use case

2021-11-16 20:44 UTC, ldts commented on libseteec/src/apdu_pta.h
> + * [in]  memref[2].buffer     source data (raw APDU request frame data).
ok. is this the last set of changes or should I hold back?

2021-11-16 21:04 UTC, ldts commented
@etienne-lms as with  https://github.com/OP-TEE/optee_os/pull/4935 I'll wait for a few days for all comments at this point so we can wrap it up. Please let me know when you are done with the review so I push one last time.

2021-11-17 07:59 UTC, etienne-lms commented on libseteec/include/se_tee.h
> + * state and the keys are derived from the HUK instead of read from secure
> is exactly the same case...however RPMB is a better known use case

Known from you maybe, not from me (the fact a huk may change).
I meant there is no such warning inline description in OP-TEE libs/suppliant when accessing RPMB. So I think the Secure Element interface API from optee_client should not specifically detail how maybe a platform handles SE keys, known that each platform may have specific constraints and pitfalls on how keys are provisioned, derived, revoked, ... . Optee_docs is by far a better place to explain specifc constraints, IMO.

2021-11-17 08:04 UTC, etienne-lms commented on libseteec/src/apdu_pta.h
> + * [in]  memref[2].buffer     source data (raw APDU request frame data).
I can't tell by now. 
I do appreciate time spent by reviewers on my changes to have them merged in the best possible state. I hope you do also.

2021-11-17 10:25 UTC, ldts commented on libseteec/src/apdu_pta.h
> + * [in]  memref[2].buffer     source data (raw APDU request frame data).
@etienne-lms absolutely!!

2021-11-17 11:03 UTC, ldts commented on libseteec/src/apdu_pta.h
> + * [in]  memref[2].buffer     source data (raw APDU request frame data).
hi @etienne-lms I added a diagram to the PR (https://github.com/OP-TEE/optee_client/pull/290 ) to bring in some clarity to what we are doing

2021-11-22 20:06 UTC, ldts commented
a week with no comments. can we merge please?

2021-11-23 07:59 UTC, ldts commented
if the interface should expand - I added an additional commit as an example -  should we keep separate simple PTAs that interface to crypto_se.h or a single one with an expanding set of functions.

I dont think this interface will grow much since _everything_ can be done using the APDU superset but I thought I'd ask.

2021-11-23 08:10 UTC, ldts commented
rebased

2021-11-23 10:02 UTC, jforissier reviewed
With my comments below addressed:
`Acked-by: Jerome Forissier <jerome@forissier.org>`

2021-11-23 10:02 UTC, jforissier commented on libseteec/CMakeLists.txt
> +find_package(Threads REQUIRED)
Not needed anymore

2021-11-23 10:02 UTC, jforissier commented on libseteec/CMakeLists.txt
> +	PRIVATE pthread
Not needed anymore

2021-11-23 10:02 UTC, jforissier commented on libseteec/CMakeLists.txt
> +	PRIVATE m
Is `libm` required?

2021-11-23 10:19 UTC, ldts commented on libseteec/CMakeLists.txt
> +	PRIVATE pthread
pthread is not needed? why not?

2021-11-23 10:19 UTC, ldts commented on libseteec/CMakeLists.txt
> +find_package(Threads REQUIRED)
could you explain why please?

2021-11-23 10:31 UTC, jforissier commented on libseteec/CMakeLists.txt
> +	PRIVATE pthread
Oh sorry, I thought you had removed all pthread calls but I see you're still using a mutex to ensure single initialization. That's fine.
`pthread_once()` would be slightly better for this purpose but the difference is not massive ;-)

2021-11-23 10:33 UTC, ldts commented on libseteec/CMakeLists.txt
> +	PRIVATE m
no, I dont think so, I will remove

2021-11-23 10:45 UTC, jforissier commented on libseteec/Makefile
> +LIBSETEEC_LFLAGS	:= $(LDFLAGS) -L$(OUT_DIR)/../libteec -lteec
`-lpthread` seems to be missing here, but there is a more fundamental issue with existing code. In theory any code using pthreads (here `libteec`, `tee-supplicant`, and now `libseteec`) should have `-pthreads` in C flags and link flags. Note that when `-pthread` is used at link time, `-lpthread` is not needed. This is because `-pthreads` defines some macros such as `_REENTRANT` etc.
I suggest adding `-lpthread` here for consistency and we will deal with the theoretical `-pthreads` issue later (since we have not yet seen any issue with the lack of this flag).

2021-11-23 10:50 UTC, ldts commented on libseteec/Makefile
> +LIBSETEEC_LFLAGS	:= $(LDFLAGS) -L$(OUT_DIR)/../libteec -lteec
funny, was just looking into the exact same thing...and I was wondering how pkcs11 can work since I just borrowed the makefile from there. sure will add!

2021-11-23 13:37 UTC, jforissier commented
@etienne-lms do you want to provide an ack/r-b? since you commented

2021-11-23 14:59 UTC, etienne-lms commented
ok, i'll make another review round.

Note there is something that bothers me. I don't want to block this P-R with that, so i stated it here just to get some feedback. The APIs defined for this library do not identify the target secure element to connect to. What if there are several SEs under OP-TEE core control? Should there be a notion a "session" to the secure element provided by the API?

2021-11-23 16:18 UTC, ldts commented
right, I think the only use case where that would make sense is on a platform that needs a number of asym key-pairs that exceeds the memory in the SE (~64KB in the SE051).

Notice that for performance reasons, only ECC/RSA sign/verify (perhaps RNG) are usually configured to be provided by the NXP SE driver: the cost of transferring data on the i2c/spi bus plus the SCP03 encryption/decryption is not neglect-able. Other crypto operations can go to CAAM (on iMX or tomcrypt). That is also why I opted for not pushing more symmetric ciphers, HMAC and other supported operations (although I could if there is demand for it).

So I think what you say makes sense; I also believe that SE vendors are choosing the NVM memory in their devices for the average user....so while I do agree with extending support for any number of concurrent secure elements, maybe that can be abstracted once the first one is merged? I could try adding support for two SE050s at a later time (also if there is demand for it...maybe SE vendors increase the NVM as time goes by)

if you think what I tried to explain above is enough for adding a session field to the APDU interface then I can do it of course.

2021-11-24 12:09 UTC, etienne-lms requested changes
Should rename _adpu_ta.h_ to _pta_apdu.h_ and update its content.
It should be enough (IMO) to add an inline comment stating type IDs exposed by the PTA and by the lib are the same. Otherwise, eitehr assert at build time, or add a (somewhat useless) conversion as done in optee_os between PTA API and crypto_se API.

2021-11-24 12:09 UTC, etienne-lms commented on libseteec/src/apdu_pta.h
> +
type hints missing.
Update this file from pta_adpu.h proposed in https://github.com/OP-TEE/optee_os/pull/4935.

2021-11-24 13:11 UTC, etienne-lms commented
> if you think what I tried to explain above is enough for adding a session field to the APDU interface then I can do it of course.

No need to add a session field. We would rather need a clean API for session management. Let's see that when there's a need and the lib API will likely evolve with new API functions.

2021-11-24 15:06 UTC, etienne-lms commented on libseteec/src/se.c
> +		return SER_CANT_OPEN_SESSION;
open session only after type sanitation.

2021-11-24 15:14 UTC, etienne-lms reviewed
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

2021-11-24 16:21 UTC, ldts commented
@etienne-lms awesome. thanks

2021-11-25 16:00 UTC, ldts commented on libseteec/include/se_tee.h
> + * Generates the board specific SCP03 keys and writes them in the Secure Element
well no, key rotation is key rotation...key generation is a different concept.

2021-11-25 18:17 UTC, ldts commented
@jforissier I think this PR is now reviewed

2021-11-26 08:09 UTC, jforissier commented
@ldts yes, thanks.

2021-11-26 08:09 UTC, merged