Fixed libteec function mmap_paddr mmap size problem
OP-TEE/optee_client pull request #325
Opened 2022-10-11 03:58 UTC by kanyuelei

#318 
Fixed libteec function "mmap_paddr" mmap size problem

2022-10-13 09:23 UTC, etienne-lms requested changes
Thanks @kanyuelei for the fix.
Could you change the commit message? It would need a header line and a reference to the OP-TEE issue you created, for convenience, see [contribution#commit-message](https://optee.readthedocs.io/en/latest/general/contribute.html#commit-messages). And your `Signed-of-by:` tag (with your real name, see [contribution-dev-certif-of-origin](https://optee.readthedocs.io/en/latest/general/contribute.html#developer-certificate-of-origin)).
Somethink like:
```
libteec: fix memory mapping function in benchmark

Fixed libteec function mmap_paddr mmap() size problem reported in [1].

Link: [1] https://github.com/OP-TEE/optee_client/issues/318
Signed-off-by: ...
```

Then you'll need to also add the review tags, as mine below:
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`.

@Jens, @jforissier, it would be nice this gets into 3.19.0 tag.

2022-10-13 09:26 UTC, jenswi-linaro commented
With @etienne-lms' comments addressed:
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

2022-10-17 08:24 UTC, jforissier commented
@kanyuelei would you mind updating the commit as requested by @etienne-lms and also add @jenswi-linaro's `Acked-by` tag? Thanks.

2022-10-17 08:47 UTC, closed without merging

2022-10-17 10:17 UTC, etienne-lms commented
@kanyuelei, it seems you accidently closed this P-R while your latest commit is fine.

2022-10-17 12:08 UTC, jforissier commented
> @kanyuelei, it seems you accidently closed this P-R while your latest commit is fine.

I've merged #326.