Correct some pkgconfig file errors
OP-TEE/optee_client pull request #337
Opened 2022-11-26 14:43 UTC by nhorman

@eli-schwartz noted a few shortocomings in the pkgconfig file added in PR 334:
* Failure to honor CMAKE_INSTALL_LIBDIR/CMAKE_INSTALL_INCLUDEDIR
* duplication of ldflags in the Libs.private section

This PR fixes those, by:
* Using cmake_path to construct the full lib/include paths prior to doing macro expansion on the pc.in file
* removing the duplication library flags in the private section for static linking

Signed-off-by: Neil Horman <nhorman@gmail.com>

2022-11-27 02:00 UTC, eli-schwartz requested changes

2022-11-27 02:00 UTC, eli-schwartz commented on libteec/libteec.pc.in
>  Requires.private: @pc_req_private@
AFAICT `pc_req_private` is also not being used anywhere yet?

2022-11-28 13:59 UTC, nhorman commented on libteec/libteec.pc.in
>  Requires.private: @pc_req_private@
removed

2022-12-06 09:27 UTC, jforissier commented
@nhorman please consolidate. It seems to me there should be 3 commits in the end, in that order:
1. cmake: introduce join_paths()
2. cmake: honor CMAKE_INSTALL_LIBDIR/CMAKE_INSTALL_INCLUDEDIR
3. pkgfconfig: remove duplicate flags and unused variables

2022-12-07 11:33 UTC, eaaltonen commented
@nhorman, @eli-schwartz: can you clarify your use case a bit? Are you setting some `CMAKE_INSTALL_LIBDIR` locations or?
I'd like to understand why the default
```
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib
```
pattern from https://people.freedesktop.org/~dbn/pkg-config-guide.html is not sufficient.

2022-12-07 12:51 UTC, nhorman commented
@eaaltonen its for exactly the reason that @eli-schwartz noted above and in PR #334 - because using that pattern fails to honor the cmake macros CMAKE_INSTALL_LIBDIR and CMAKE_INSTALL_INCLUDEDIR.  There is no reason those paths will necessarily be set to the same base location, or end in lib | include for that matter.  Nominally they will, but its not a guarantee.

Also, the freedesktop defined pattern is really more of a guideline anyway, often the default pattern is insufficient for multiarch environment (for instance most distros will set libdir to /usr/lib64 on aarch64/x86-64 platforms, so ${prefix}/lib isn't correct in those cases.

2022-12-07 13:11 UTC, eli-schwartz commented
It's not even a default or a guideline -- it's an example.

Examples, by their very definition, are not intended to be treated specially and used verbatim. That example, in particular, if used verbatim, would mean hardcoding `prefix=/usr/local`and NOT filling it in with the value of CMAKE_INSTALL_PREFIX.

2023-01-12 01:52 UTC, closed without merging