Fix Memory Leak in serialize_indirect_attribute()
OP-TEE/optee_client pull request #390
Opened 2024-09-13 01:29 UTC by hoyong2007

Add `release_serial_object(obj2)` to release obj2 
before `serialize_indirect_attribute()` returns to
prevent memory leakage.

2024-09-13 01:33 UTC, hoyong2007 commented
This is a PR for issue https://github.com/OP-TEE/optee_client/issues/387

2024-09-13 05:19 UTC, etienne-lms requested changes
Could you format the commit message in a more standard way? A header line (74 char/max, starting with `libckteec: ` + a short description + your `Signed-off-by:` tag. Please also add a `Link:` tag to reference the Issue entry this change fixes, as well as a `Fixes:` tag referencing the faulty commit. Something like:
```
libckteec: fix memory allocation leakage on template serialization

Fix memory allocation leakage with a call to release_serial_object()
to release obj2 before serialize_indirect_attribute() returns.

Link: https://github.com/OP-TEE/optee_client/issues/387
Fixes: e88c264ba358 ("libckteec: helper function to serialize a attribute template")
Signed-off-by: REAL-NAME <E-MAIL-ADDRESS>
```
There are few indications in the [*contribution documentation*](https://optee.readthedocs.io/en/latest/general/contribute.html#commit-messages). See also the other commits in **optee_client.git** history.

2024-09-17 14:13 UTC, etienne-lms commented
Thanks for the fix. Could you squash the 2 commits into a single one.
You can apply my R-b tag: `Reviewed-by: Etienne Carriere <etienne.carriere@foss.st.com>`.

2024-09-23 15:12 UTC, etienne-lms commented
Looks all good to me.
@jforissier, could you enable CI tests for this change?

2024-09-23 15:16 UTC, jforissier commented
> @jforissier, could you enable CT tests for this P-R?

Sure, done.

2024-09-23 15:54 UTC, etienne-lms approved these changes
Thanks.
All good. Ready to merge.

2024-09-24 08:24 UTC, merged